# Dictionary of all 201 families in Bentham & Hooker classification system
ALL_FAMILY_DESCRIPTIONS = {
    # Polypetalae - Thalamiflorae
    "RANUNCULACEAE": "Herbs with alternate dissected leaves. Flowers bisexual, parts free and spirally arranged, stamens numerous, apocarpous.",
    "DILLENIACEAE": "Shrubs, trees, or climbers with alternate simple leaves. Flowers with numerous stamens, carpels separate with arillate seeds.",
    "CALYCANTHACEAE": "Aromatic shrubs with opposite leaves. Flowers with numerous tepals, stamens, and free carpels inside a hollow receptacle.",
    "MAGNOLIACEAE": "Aromatic trees/shrubs with stipules. Showy flowers with spirally arranged perianth, numerous stamens and carpels on an elongated receptacle.",
    "ANONACEAE": "Aromatic trees or shrubs. Flowers trimerous, sepals 3, petals 6, numerous stamens, apocarpous carpels forming aggregate fruit.",
    "MENISPERMACEAE": "Dioecious twining vines. Leaves alternate, palmately veined. Flowers small, unisexual, trimerous, drupaceous fruits with curved seeds.",
    "BERBERIDACEAE": "Herbs or shrubs. Flowers trimerous, stamens opening by valves, single carpel with basal placentation.",
    "NYMPHAEACEAE": "Aquatic herbs with floating peltate leaves. Flowers large, showy, solitary, numerous petals and stamens on a fleshy disc.",
    "SARRACENIACEAE": "Carnivorous herbs with pitcher-shaped leaves. Flowers large, nodding, style forming a broad umbrella-like structure.",
    "PAPAVERACEAE": "Herbs with milky/colored latex. Sepals 2-3 caducous, petals 4, stamens numerous, parietal placentation.",
    "CRUCIFERAE": "Herbs with watery biting sap. Flowers cruciform, tetradynamous stamens, siliqua fruit with false septum.",
    "CAPPARIDEAE": "Herbs/shrubs with alternate leaves. Flowers with prominent gynophore or androgynophore, parietal placentation.",
    "RESEDACEAE": "Herbs with alternate leaves. Inflorescence a spike or raceme, flowers zygomorphic, stamens on an eccentric disc.",
    "CISTINEAE": "Shrubs or herbs. Flowers regular, showy, sepals 3-5 convolute, stamens numerous, parietal placentation.",
    "VIOLARIEAE": "Herbs or shrubs, alternate stipulate leaves. Flowers zygomorphic, lower petal spurred, stamens 5 forming a ring around ovary.",
    "CANELLACEAE": "Aromatic trees with pellucid-dotted leaves. Flowers regular, stamens fused into a tube, parietal placentation.",
    "BIXINEAE": "Trees or shrubs with alternate leaves. Flowers regular, stamens numerous, capsule fruit with seeds often surrounded by colored pulp.",
    "PITTOSPOREAE": "Trees/shrubs with resin ducts. Leaves alternate, entire. Flowers regular, pentamerous, parietal/axile placentation.",
    "TREMANDREAE": "Xerophytic shrubs with heath-like habit. Flowers solitary, regular, anthers opening by terminal pores, seeds arillate.",
    "POLYGALAE": "Herbs or shrubs. Zygomorphic papilionaceous-like flowers, 5 sepals (2 large wing-like), 8 stamens fused in a split tube.",
    "VOCHYSIACEAE": "Trees/shrubs with resinous sap. Flowers irregular, one calyx lobe spurred, single stamen, capsule or winged samara fruit.",
    "FRANKENIACEAE": "Halophytic salt-glandular herbs. Leaves opposite, small. Flowers regular, petals clawed, parietal placentation.",
    "CARYOPHYLLEAE": "Herbs with swollen nodes, opposite entire leaves. Flowers regular, clawed petals, free-central placentation.",
    "PORTULACEAE": "Succulent herbs with opposite or alternate leaves. Flowers regular, sepals 2, stamens opposite petals, capsule opening by a lid.",
    "TAMARISCINEAE": "Shrubs or trees with scale-like leaves. Flowers small in spikes, petals free, seeds with a tuft of hairs.",
    "ELATINEAE": "Small aquatic or moisture-loving herbs. Leaves opposite, stipulate. Flowers small, axillary, axile placentation.",
    "HYPERICINEAE": "Herbs or shrubs with gland-dotted opposite leaves. Flowers yellow, stamens numerous and united in 3-5 bundles.",
    "GUTTIFERAE": "Trees/shrubs with resinous yellow sap. Flowers regular, stamens numerous and clustered, seeds without endosperm.",
    "TERNSTROEMIACEAE": "Trees or shrubs. Alternate simple leaves without stipules. Flowers solitary, regular, stamens numerous.",
    "DIPTEROCARPEAE": "Resinous forest trees. Flowers sweet-scented, calyx lobes developing into long wings on the fruit.",
    "CHLENACEAE": "Trees/shrubs endemic to Madagascar. Flowers showy, surrounded by an involucre, stamens numerous, fruit a capsule.",
    "MALVACEAE": "Herbs/shrubs with stellate hairs, alternate stipulate leaves. Flowers regular, stamens fused in a monadelphous tube, anthers 1-loculed.",
    "STERCULIACEAE": "Herbs/trees with stellate hairs. Alternate simple/compound leaves. Flowers regular, monadelphous stamens, anthers 2-loculed.",
    "TILIACEAE": "Trees/shrubs with mucilage. Leaves alternate, stipulate. Flowers regular, stamens numerous and free or in bundles.",
    
    # Polypetalae - Disciflorae
    "LINEAE": "Herbs or shrubs. Leaves alternate, entire. Flowers regular, pentamerous, stamens fused at base, ovary superior.",
    "HUMIRIACEAE": "Balsamiferous trees/shrubs. Leaves alternate. Flowers regular, stamens 10-30 with expanded connectives, drupe fruit.",
    "MALPIGHIACEAE": "Woody climbers with T-shaped hairs. Flowers clawed, calyx with prominent glands, winged samara fruits.",
    "ZYGOPHYLLEAE": "Succulent herbs/shrubs of arid zones. Leaves opposite, pinnate. Flowers regular, stamens with basal scales.",
    "GERANIACEAE": "Herbs with glandular hairs. Alternate lobed leaves. Flowers regular, pentamerous, fruit a schizocarp with elastic awns.",
    "RUTACEAE": "Aromatic plants with pellucid gland-dotted leaves. Flowers regular, stamens on a prominent nectar disc.",
    "SIMARUBEAE": "Trees or shrubs with bitter bark. Leaves alternate, pinnate. Flowers small, unisexual or bisexual, disc present.",
    "OCHNACEAE": "Trees or shrubs with shiny serrate leaves. Flowers yellow, stamens numerous, anthers opening by pores, torus enlarged in fruit.",
    "BURSERACEAE": "Resinous trees/shrubs with aromatic balsam. Leaves alternate, pinnate. Flowers small, nectar disc prominent.",
    "MELIACEAE": "Trees/shrubs with pinnate exstipulate leaves. Flowers in panicles, stamens fused into a characteristic tube.",
    "CHAILLETIACEAE": "Shrubs or trees. Leaves alternate, entire. Flowers small, petals bifid, ovary superior, drupe fruit.",
    "OLACINEAE": "Trees or shrubs, often hemiparasitic. Flowers small, calyx enlarging in fruit, disc cup-shaped.",
    "ILICINEAE": "Evergreen trees or shrubs. Leaves alternate, simple. Flowers small, unisexual, drupe with multiple pyrenes.",
    "CYRILLACEAE": "Shrubs or small trees. Leaves alternate, simple, exstipulate. Flowers small in racemes, stamens 5 or 10, fruit a capsule or drupe.",
    "CELASTRINEAE": "Shrubs or trees. Leaves opposite or alternate. Flowers small, regular, disc flat and adnate to calyx, stamens alternate with petals.",
    "STACKHOUSIEAE": "Herbs with alternate simple leaves. Flowers in spikes, corolla tubular with free claws, fruit of 3-5 eremicos.",
    "RHAMNEAE": "Trees/shrubs, often thorny. Leaves simple, stipules often modified into spines. Stamens opposite the small hooded petals.",
    "AMPELIDEAE": "Climbing plants with tendrils opposite the leaves. Flowers small, stamens opposite petals, fruit a berry.",
    "SAPINDACEAE": "Trees/shrubs, compound leaves. Flowers small, irregular, nectar disc present. Seeds often arillate.",
    "SABIACEAE": "Trees or shrubs. Leaves alternate, simple or pinnate. Flowers irregular, stamens opposite petals, drupe fruit.",
    "ANACARDIACEAE": "Trees/shrubs with resinous/milky sap. Flowers small, disc present, single carpel fertile, drupe fruit.",
    "CORIARIEAE": "Shrubs with angled branchlets and opposite leaves. Flowers small, petals fleshy and accrescent in fruit.",
    "MORINGEAE": "Deciduous trees with corky bark, compound leaves. Flowers irregular, 5 unequal petals, stamens 5, capsule elongate.",
    
    # Polypetalae - Calyciflorae
    "CONNARACEAE": "Woody climbers or shrubs. Leaves alternate, pinnate. Flowers regular, carpels 5 free, follicular fruits.",
    "LEGUMINOSAE": "Herbs/trees/shrubs, stipulate leaves. Flowers zygomorphic or regular, single carpel, legume or pod fruit.",
    "ROSACEAE": "Herbs/shrubs/trees, stipulate leaves. Flowers perigynous with hypanthium, stamens numerous, carpels free or fused.",
    "SAXIFRAGEAE": "Herbs or shrubs. Leaves alternate or opposite. Flowers regular, perigynous, carpels 2 fused at base, styles free.",
    "CRASSULACEAE": "Succulent herbs with opposite/alternate leaves. Flowers regular, carpels free with scale at base, follicle fruits.",
    "DROSERACEAE": "Insectivorous glandular herbs. Leaves in rosettes with glandular tentacles, circinate vernation.",
    "HAMAMELIDEAE": "Shrubs or trees with stellate hairs. Leaves alternate. Flowers regular or apetalous, ovary half-inferior.",
    "BRUNIACEAE": "Heath-like shrubs endemic to South Africa. Flowers small in dense heads, calyx adnate to ovary.",
    "HALORAGEAE": "Aquatic or terrestrial herbs. Leaves whorled or alternate. Flowers small, unisexual or bisexual, inferior ovary.",
    "RHIZOPHOREAE": "Mangrove trees with stilt roots, viviparous. Flowers bisexual, petals fringed, inferior ovary.",
    "COMBRETACEAE": "Trees, shrubs, or climbers. Leaves simple, alternate/opposite. Flowers regular, inferior ovary, winged fruit.",
    "MYRTACEAE": "Aromatic trees/shrubs with gland-dotted leaves and intra-marginal vein. Flowers with numerous free stamens.",
    "MELASTOMACEAE": "Herbs/shrubs with opposite 3-9 palmately veined leaves. Curved stamens opening by apical pores.",
    "LYTHRARIEAE": "Herbs, shrubs, or trees with opposite leaves. Flowers regular, calyx tube persistent, crinkled petals.",
    "ONAGRARIEAE": "Herbs or shrubs. Flowers regular, 4-merous, hypanthium tube present, inferior ovary.",
    "SAMYDACEAE": "Trees or shrubs. Leaves alternate, simple. Flowers regular, stamens often alternating with staminodes, capsule fruit.",
    "LOASEAE": "Herbs, often with stinging hairs. Flowers regular, petals hood-like, stamens numerous, capsule fruit.",
    "TURNERACEAE": "Herbs or shrubs. Leaves alternate, serrate. Flowers regular, petals yellow and inserted on calyx tube, capsule fruit.",
    "PASSIFLOREAE": "Climbers with axillary tendrils. Flowers regular, large, with a conspicuous corona of threads.",
    "CUCURBITACEAE": "Climbing herbs with tendrils. Leaves palmate. Flowers unisexual, yellow, inferior ovary, pepo fruit.",
    "BEGONIACEAE": "Succulent herbs with asymmetric leaves. Flowers unisexual, tepals colorful, capsule fruit 3-winged.",
    "DATISCEAE": "Dioecious herbs or trees. Leaves alternate. Flowers unisexual, apetalous, inferior ovary, capsule opening at apex.",
    "CACTEAE": "Succulent xerophytes, stems fleshy and spiny (areoles), leaves reduced. Flowers showy, solitary, inferior ovary.",
    "FICIOIDEAE": "Succulent herbs/shrubs. Flowers regular, petals absent or replaced by petaloid staminodes, capsule fruit.",
    "UMBELLIFERAE": "Herbs with furrowed stems, compound sheath-like leaves. Flowers in umbels, schizocarp fruit (cremocarp).",
    "ARALIACEAE": "Woody plants, leaves compound. Flowers in umbels, inferior ovary, drupe or berry fruit.",
    "CORNACEAE": "Trees or shrubs. Leaves opposite, simple. Flowers small, regular, inferior ovary, drupe fruit.",
    
    # Gamopetalae - Inferae
    "CAPRIFOLIACEAE": "Shrubs or vines. Leaves opposite, exstipulate. Flowers regular or irregular, inferior ovary, berry fruit.",
    "RUBIACEAE": "Opposite entire leaves with interpetiolar stipules. Flowers sympetalous, inferior ovary.",
    "VALERIANEAE": "Herbs with opposite leaves. Flowers asymmetric, calyx forming a pappus in fruit, single fertile locule.",
    "DIPSACEAE": "Herbs, leaves opposite. Flowers in dense heads surrounded by an involucre, calyx pappus-like.",
    "CALCEREAE": "Small herbs. Flowers regular or irregular, inferior ovary, fruit a capsule or drupe.",
    "COMPOSITAE": "Herbs/shrubs. Flowers in heads (capitula) with involucre, syngenesious anthers, pappus calyx, cypsela fruit.",
    "STYLIDIEAE": "Herbs with leaves in rosettes. Flowers irregular, stamens and style fused into a sensitive column.",
    "GOODENOVIEAE": "Herbs or shrubs. Flowers irregular, corolla split on one side, style with a pollen-collecting cup (indusium).",
    "CAMPANULACEAE": "Herbs with milky sap. Leaves alternate. Flowers regular, bell-shaped corolla, ovary inferior.",
    
    # Gamopetalae - Heteromerae
    "VACCINIACEAE": "Shrubs or small trees. Leaves alternate. Flowers regular, sympetalous, ovary inferior, fruit a berry.",
    "ERICACEAE": "Shrubs with alternate needle-like or leathery leaves. Flowers urn-shaped, anthers opening by pores, superior ovary.",
    "MONOTROPEAE": "Aphyllous saprophytic herbs, white or colorful. Flowers solitary or in racemes, superior ovary.",
    "EPACRIDEAE": "Heath-like shrubs. Leaves small, parallel-veined. Flowers regular, stamens 5, anthers opening by a single slit.",
    "DIAPENSIACEAE": "Low alpine herbs or subshrubs. Leaves small, crowded. Flowers regular, stamens 5, staminodes present.",
    "LENNOACEAE": "Root-parasitic herbs, brown or yellow, without chlorophyll. Flowers regular in heads or spikes.",
    "PLUMBAGINEAE": "Herbs/shrubs. Flowers regular, calyx plaited, 5 styles, single ovule on basal funicle.",
    "PRIMULACEAE": "Herbs, leaves in rosettes. Flowers regular, stamens opposite petals, free-central placentation.",
    "MYRSINEAE": "Trees/shrubs. Leaves alternate, gland-dotted. Flowers regular, stamens opposite petals, drupe or berry fruit.",
    "SAPOTACEAE": "Trees/shrubs with milky latex. Flowers regular, sympetalous, stamens in whorls, superior ovary.",
    "EBENACEAE": "Dioecious trees/shrubs, black wood. Flowers unisexual, regular, calyx persistent and accrescent, berry fruit.",
    "STYRACEAE": "Trees or shrubs. Leaves alternate, simple. Flowers regular, stamens twice as many as corolla lobes, drupe fruit.",
    
    # Gamopetalae - Bicarpellatae
    "OLEACEAE": "Trees or shrubs. Leaves opposite. Flowers regular, tetramerous, stamens 2, ovary superior and bilocular.",
    "SALVADORACEAE": "Shrubs or trees. Leaves opposite, entire. Flowers small, regular, tetramerous, stamens 4, drupe fruit.",
    "APOCYNACEAE": "Plants with milky latex. Opposite leaves. Flowers regular, sympetalous, stamens 5, fruit of 2 follicles, seeds with a tuft of hairs.",
    "ASCLEPIADEAE": "Plants with milky latex. Opposite leaves. Flowers regular, corona present, pollen in pollinia, gynostegium.",
    "LOGANIACEAE": "Trees or shrubs. Leaves opposite, stipulate. Flowers regular, sympetalous, ovary superior, capsule or berry fruit.",
    "GENTIANEAE": "Herbs, opposite entire leaves. Flowers regular, sympetalous, ovary superior, parietal placentation.",
    "POLEMONIACEAE": "Herbs with alternate leaves. Flowers regular, sympetalous, ovary superior and tricarpellary, capsule fruit.",
    "HYDROPHYLLACEAE": "Herbs with alternate leaves. Inflorescence a scorpioid cyme, flowers regular, capsule fruit.",
    "BORAGINEAE": "Hispid herbs with scorpioid cymes. Flowers regular, sympetalous, ovary deeply 4-lobed, gynobasic style.",
    "CONVOLVULACEAE": "Twining herbs/shrubs. Flowers funnel-shaped, sympetalous, ovary superior, bicarpellate.",
    "SOLANACEAE": "Herbs/shrubs with alternate leaves. Flowers regular, sympetalous, ovary superior, placenta swollen, seeds endospermic.",
    "SCROPHULARINEAE": "Herbs/shrubs. Flowers zygomorphic, bilabiate, didynamous stamens, superior ovary with numerous ovules on axile placenta.",
    "OROBRANCHACEAE": "Fleshy root-parasitic herbs, brown or purple. Flowers zygomorphic, parietal placentation.",
    "LENTIBULARIEAE": "Carnivorous aquatic/wetland herbs. Leaves modified into insect-trapping bladders, free-central placentation.",
    "COLUMELLIACEAE": "Shrubs or trees. Leaves opposite. Flowers irregular, stamens 2, ovary inferior, capsule fruit.",
    "GESNERACEAE": "Herbs or shrubs. Leaves opposite. Flowers zygomorphic, ovary superior or semi-inferior, parietal placentation.",
    "BIGNONIACEAE": "Trees/vines with compound leaves. Flowers large, zygomorphic, didynamous stamens, seeds winged in capsule.",
    "PEDALINEAE": "Sticky herbs with glandular hairs. Zygomorphic flowers. Fruit with hooks or spines, axile placentation.",
    "ACANTHACEAE": "Herbs with opposite leaves and cystoliths. Zygomorphic flowers, bracteate, jaculator in fruit capsule.",
    "MYOPORINEAE": "Shrubs or trees. Leaves alternate, gland-dotted. Flowers zygomorphic, drupe fruit.",
    "SELAGINEAE": "Small shrubs or herbs. Leaves alternate. Flowers zygomorphic, calyx sheath-like, ovary 2-celled.",
    "VERBENACEAE": "Quadrangular stems, opposite leaves. Zygomorphic flowers, style terminal, fruit drupe or schizocarp.",
    "LABIATAE": "Aromatic herbs, quadrangular stems, opposite leaves. Flowers zygomorphic, verticillaster, deeply 4-lobed ovary, gynobasic style.",
    "PLANTAGINEAE": "Herbs, leaves in rosettes. Flowers small, green, scarious perianth, capsule opening by a lid (pyxidium).",
    
    # Monochlamydeae
    "NYCTAGINEAE": "Opposite leaves. Flowers small surrounded by colorful bracts, perianth tubular, 1-seeded anthocarp fruit.",
    "ILLECEBRACEAE": "Small herbs, leaves opposite. Flowers small, green, perianth scarious, single seed.",
    "AMARANTACEAE": "Herbs with scarious bracteate flowers, perianth dry and membranous, circumscissile capsule.",
    "CHENOPODIACEAE": "Halophytic or succulent herbs. Flowers small, green, perianth fleshy or membranous, fruit a utricle.",
    "PHYTOLACCACEAE": "Herbs or shrubs. Flowers small, green or reddish, carpels numerous in a ring, fruit a berry.",
    "BATIDEAE": "Maritime succulent shrubs. Leaves opposite, small. Flowers unisexual in spikes, fruit a collective cone.",
    "POLYGONACEAE": "Herbs with swollen nodes and ochreate stipules. Flowers small, perianth tepaloid, fruit a triangular achene.",
    "PODOSTEMONACEAE": "Submerged freshwater thalloid herbs. Flowers small, apetalous, capsule fruit.",
    "NEPENTHACEAE": "Carnivorous climbing pitchers. Leaves modified to pitchers with lid, dioecious, capsule fruit.",
    "CYTINACEAE": "Fleshy root-parasites, without chlorophyll. Flowers unisexual in heads, inferior ovary.",
    "ARISTOLOCHIACEAE": "Herbs or woody vines. Flowers pipe-shaped, dark and fetid, perianth 3-lobed, inferior ovary.",
    "PIPERACEAE": "Herbs/shrubs with swollen nodes, aromatic. Flowers tiny in dense spikes, drupe fruit.",
    "CHLORANTACEAE": "Aromatic shrubs or herbs. Leaves opposite. Flowers tiny, unisexual or bisexual, single carpel.",
    "MYRISTICEAE": "Dioecious trees, red sap. Flowers small, unisexual, single seed with colored aril (mace).",
    "MONIMIACEAE": "Aromatic trees or shrubs. Opposite leaves. Flowers unisexual, carpels numerous in a hollow receptacle.",
    "LAURINEAE": "Aromatic trees/shrubs. Flowers regular, anthers opening by 2-4 valves, single seed drupe.",
    "PROTEACEAE": "Trees or shrubs. Leaves alternate, leathery. Flowers showy, 4 valvate tepals, stamens opposite tepals.",
    "THYMELAEACEAE": "Shrubs or trees, tough fibrous bark. Flowers tubular, 4-5 lobed, single carpel, superior ovary.",
    "PENAEACEAE": "Evergreen ericoid shrubs. Leaves small, opposite. Flowers regular, 4-lobed perianth, ovary superior.",
    "ELAEAGNACEAE": "Shrubs or trees with silvery/brown stellate scales. Flowers regular, single seed.",
    "LORANTHACEAE": "Green hemiparasitic shrubs on tree branches. Flowers showy, inferior ovary, berry with viscin.",
    "SANTALACEAE": "Hemiparasitic trees or shrubs. Flowers small, green, inferior ovary, drupe or nut fruit.",
    "BALANOPHOREAE": "Fleshy root-parasitic herbs, yellow or red. Flowers small in dense club-shaped inflorescences.",
    "EUPHORBIACEAE": "Milky sap, unisexual flowers, tricarpellate syncarpous ovary, regma fruit.",
    "BALANOPEAE": "Dioecious trees/shrubs. Leaves alternate. Flowers unisexual, drupe fruit.",
    "URTICACEAE": "Herbs/shrubs, stinging hairs or cystoliths. Flowers small, unisexual, stamens infolded in bud.",
    "PLATANACEAE": "Deciduous trees with scaling bark. Leaves palmate. Flowers unisexual in dense globose heads.",
    "LEITNERIEAE": "Dioecious shrubs with very light wood. Leaves alternate. Flowers in catkins, drupe fruit.",
    "JUGLANDEAE": "Deciduous aromatic trees. Leaves pinnate. Flowers unisexual, male in catkins, fruit a drupe or nut.",
    "MYRICACEAE": "Aromatic shrubs or trees. Leaves alternate, resinous-dotted. Flowers in catkins, drupe fruit with wax.",
    "CASUARINEAE": "Jointed branchlets, scale leaves. Male flowers in spikes, female in heads forming woody cones.",
    "CUPULIFERAE": "Trees/shrubs. Leaves alternate, simple. Flowers unisexual, male in catkins, female in involucre (cupule), nut fruit.",
    "SALICINEAE": "Dioecious trees/shrubs. Leaves alternate. Flowers in catkins, seeds with a tuft of long silky hairs.",
    "LACISTEMACEAE": "Shrubs or trees. Leaves alternate. Flowers small in catkin-like spikes, single stamen, capsule fruit.",
    "EMPETRACEAE": "Heath-like evergreen shrubs. Leaves small, crowded. Flowers small, unisexual or bisexual, berry-like drupe.",
    "CERATOPHYLLEAE": "Submerged rootless aquatic herbs. Leaves whorled, dichotomously dissected. Flowers unisexual, solitary.",
    
    # Gymnospermae
    "GNETACEAE": "Vessels present in xylem. Leaves opposite, broad. Cones compound with outer envelope.",
    "CONIFERAE": "Wood without vessels. Needles/scale leaves, resin ducts. Unisexual cones, seeds winged or fleshy.",
    "CYCADACEAE": "Wood without vessels. Palm-like unbranched trunk, pinnate compound leaves. Large terminal cones.",
    
    # Monocotyledonae
    "HYDROCHARIDEAE": "Submerged or floating aquatic herbs. Flowers regular, unisexual, spathe present, inferior ovary.",
    "BURMANNIACEAE": "Small autotrophic or saprophytic herbs. Flowers regular, perianth tubular, winged ovary, inferior.",
    "ORCHIDEAE": "Epiphytic/terrestrial herbs. Zygomorphic resupinate flowers, pollinia, column (gynostemium).",
    "SCITAMINEAE": "Aromatic rhizomatous herbs. Zygomorphic flowers, 1 fertile stamen or staminodes, inferior ovary.",
    "BROMELIACEAE": "Epiphytic herbs. Leaves xerophytic in a rosette. Flowers regular, colorful bracts, inferior ovary.",
    "HAEMODORACEAE": "Perennial herbs. Leaves equitant. Flowers regular, perianth persistent, ovary inferior or superior.",
    "IIRIDEAE": "Perennial herbs with bulbs/rhizomes. Leaves equitant. Flowers regular or irregular, stamens 3, inferior ovary.",
    "AMARYLLIDEAE": "Bulbous herbs. Scapose umbellate inflorescence with spathe. Flowers regular, trimerous, inferior ovary.",
    "TACCACEAE": "Tuberous herbs. Leaves large. Inflorescence umbel-like with long thread-like bracts, inferior ovary.",
    "DIOSCOREACEAE": "Twining vines with tuberous rhizomes. Leaves palmate. Flowers small, unisexual, inferior ovary.",
    "ROXBURGHIACEAE": "Climbing shrubs or herbs. Leaves opposite. Flowers regular, tetramerous, capsule fruit.",
    "LILIACEAE": "Bulbous/cormous herbs. Flowers regular, trimerous, 6 tepals, 6 stamens, superior ovary.",
    "PONTEDERIACEAE": "Aquatic herbs, petioles often swollen. Flowers regular, 6 tepals blue or purple, superior ovary.",
    "PHILYDRACEAE": "Herbs with equitant leaves. Flowers zygomorphic, perianth of 2 large tepals, single stamen.",
    "XYRIDEAE": "Tufted rush-like herbs. Flowers yellow in dense spikes with imbricate bracts, capsule fruit.",
    "MAYACEAE": "Small moss-like aquatic herbs. Leaves small, linear. Flowers regular, trimerous, superior ovary.",
    "COMMELINACEAE": "Succulent herbs, closed leaf sheaths. Flowers trimerous, sepals and petals distinct, superior ovary.",
    "RAPATEACEAE": "Perennial herbs. Leaves in a rosette. Inflorescence head-like on a long scape, capsule fruit.",
    "FLAGELLARIEAE": "Climbers with leaf tips modified into tendrils. Flowers small, regular, drupe fruit.",
    "JUNCACEAE": "Rush-like tufted herbs. Leaves linear or reduced. Flowers small, dry and chaffy, superior ovary.",
    "PALMAE": "Woody plants with unbranched trunk and terminal crown of pinnate/palmate leaves. Berry or drupe fruit.",
    "PANDANEAE": "Shrubs or trees with stilt roots, leaves linear and spiny-margined in spirals. Dioecious, syncarp fruit.",
    "CYCLANTHACEAE": "Palm-like or climbing herbs. Leaves deeply bifid. Inflorescence spadix with deciduous spathes.",
    "TYPHACEAE": "Marsh herbs. Leaves linear. Inflorescence a dense terminal cylindrical spike of unisexual flowers.",
    "AROIDEAE": "Tuberous herbs, leaves broad. Spadix inflorescence enclosed by a spathe, berries.",
    "LEMNACEAE": "Tiny floating thalloid aquatics without distinct stem or leaves. Flowers minute, unisexual.",
    "TRIURIDEAE": "Small saprophytic herbs without chlorophyll. Flowers unisexual, carpels numerous and free.",
    "ALISMACEAE": "Marsh or aquatic herbs. Leaves long-petioled. Flowers regular, sepals 3 green, petals 3 white, carpels numerous.",
    "NAIADACEAE": "Submerged marine or freshwater herbs. Flowers tiny, unisexual, apetalous.",
    "ERIOCAULEAE": "Tufted herbs. Inflorescence a small dense globose head of tiny unisexual flowers with scarious bracts.",
    "CENTROLEPIDEAE": "Small tufted moss-like herbs. Flowers tiny, enclosed in scarious bracts.",
    "RESTIACEAE": "Rush-like herbs with tufted stems. Leaves reduced to sheaths. Dioecious, dry chaffy perianth.",
    "CYPERACEAE": "Sedges, solid 3-angled stems, 3-ranked leaves. Flowers in spikelets, perianth of bristles, achene fruit.",
    "GRAMINEAE": "Grasses, round hollow stems, 2-ranked leaves. Inflorescence spikelet, caryopsis fruit."
}
